# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: fischeck
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  namespace: fischeck
  labels:
    app: web
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
        - name: rss-reader
          image: nickchase/rss-php-nginx:v1
          ports:
            - containerPort: 88
---
kind: Service
apiVersion: v1
metadata:
  name: fischeck
  namespace: fischeck
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 80
